### ISSUE TITLE
UX with the rating comment is a bit confusing

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#1]
In the 'You Rate' on the Member page, I wonder if it would be an improvement if there was a box around the stars widget, so that it looks like a button, then when the user mouses over it, he sees that he can also choose the number of stars. This UI element of 'text box' + star rating is unique to member and untested, so i'm not sure how intuitive it is for users.

**Comment by Real-FEELS** [comment]
The first step to improving it would be wrapping the `data-ratingsize` in another div with a class like `ratings` - let me know when this is done then I can play around with some styling. 

It would be useful to use something like Google Tag Manager on the member.cash version to see what users behaviours are, then learn and iterate form there.

**Comment by Real-FEELS** [comment]
This should be fixed

**Comment by FreeTrade** [comment]
Thanks, just a note on Google analytics, and other tracking software - yes this would be helpful to make usability improvements, but part of Member.cash brand, and hopefully its appeal, is that we don't track users behavior. Also I'm doing my level best not to allow any 3rd party hosted Javascript to run on the site to keep it secure and snappy.

**Comment by Real-FEELS** [comment]
minifying js and css for prod would help make it slightly faster too

**Comment by FreeTrade** [comment]
I agree, need a step after dev to minify. but not a pressing issue just yet
