### ISSUE TITLE
Nested comments on mobile get very narrow

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#10]
maybe reduce indentation to 1 pixel after depth of 6 as deeply nested conversation can get very narrow-

https://freetrade.github.io/memberdev/#thread?root=b7982a423ddb702a41d8f01e7449e6fb1d280ab44a2a60e331dc34ac51b9d739&post=593427051bb05309cb32288eba37f04b39d9bb20b73d0ef8d694241949bfd190

**Comment by Real-FEELS** [comment]
Would it make sense to make a (load more comments) button?

**Comment by FreeTrade** [comment]
Maybe, we can also do comment collapsing. but not sure it would solve the issue, unless the comments opened on a new page, which is kind of annoying for a user.

**Comment by Real-FEELS** [comment]
Fixed with https://github.com/FreeTrade/memberdev/pull/42
