### ISSUE TITLE
lack of spacing in notification titles

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#11]
appears like 
Reset_Jett liked yourpost0¢9 hours ago

**Comment by FreeTrade** [comment]
looks like it's trying to lay them out as a table - this works very badly on narrow screens especially

**Comment by FreeTrade** [comment]
added patch -

  .notificationtitle, .repost {
        display: inherit;
    }

**Comment by Real-FEELS** [comment]
Fixed with https://github.com/FreeTrade/memberdev/pull/42
