### ISSUE TITLE
Formatting of identicon, user, starrating

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#12]
![Capture](https://user-images.githubusercontent.com/5759305/92368114-dce26880-f129-11ea-8be7-3b24d4f75795.PNG)

Spacing feels off to me here - also, don't think the button needs to be applied - the button works well on the settings page where it it acts like a submit button on the text field, but elsewhere, it's a bit unnecessary.

**Comment by Real-FEELS** [comment]
Fixed with https://github.com/FreeTrade/memberdev/pull/42
