### ISSUE TITLE
"Currency Display: BCH" Does not properly format values > 1 million sats (~$9 USD)

### ISSUE THREAD

**Issue by OrvilleRed** [memberapp/FeelsTheme#13]
To reproduce:
Deposit 1,000,000 sats to account
Go to Settings
Set Currency Display to BCH
Observe:
Wallet displays value with one comma; there should be two
₿1,234567

**Comment by Real-FEELS** [comment]
Fixed with https://github.com/FreeTrade/memberdev/pull/42
