### ISSUE TITLE
Spacing with topic headers and h1 tag. Also no buttons?

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#18]

**Comment by Real-FEELS** [comment]
link?

**Comment by Real-FEELS** [comment]
Was the `<div class="content">` div removed?

**Comment by FreeTrade** [comment]
No, the div is there. Spacing looks fixed, but in the topic list there are large buttons, but text link buttons in the topic headers on pages for individual topics.

**Comment by Real-FEELS** [comment]
https://github.com/FreeTrade/memberdev/pull/46
