### ISSUE TITLE
Still got newlines following links in posts

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#2]

**Comment by Real-FEELS** [comment]
Please provide CSS fix you used

**Comment by Real-FEELS** [comment]
is this a dupe of #4 ?

**Comment by Real-FEELS** [comment]
Post text should be inside paragraph tag. Please make the changes to the HTML/JS
Then I will be able to target a post with only `<a>link</a>` or a post with `<p>text <a>link</a></p>`

**Comment by FreeTrade** [comment]
ok paragraph tags added.

Also, have allowed newlines in general in posts, making them more like twitter posts, less like reddit headlines.

**Comment by Real-FEELS** [comment]
Should be fixed with latest PR
