### ISSUE TITLE
Ratings tables on mobile

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#20]
Ratings tables on mobile are don't display well. open to suggestions on improving html to help.

**Comment by Real-FEELS** [comment]
You could make the stars smaller on mobile?

**Comment by FreeTrade** [comment]
I'm not sure - is it possible to affect the star size with css?

**Comment by Real-FEELS** [comment]
If you are willing to update the DOM, this is the responsive style I would prefer https://www.jering.tech/articles/card-style-css-only-responsive-tables

**Comment by FreeTrade** [comment]
Ok, looks like we just need some additional span tags. done.

**Comment by Real-FEELS** [comment]
The magic happens with `data-label=`

**Comment by FreeTrade** [comment]
Does the data-label link it to the header? If so, I guess a header is also required. Also, what if the names of the headers change, for localization for example?

**Comment by Real-FEELS** [comment]
The css will only target the `data-label=` part. So the text it contains does not matter. 

A table header `thead` is not required

**Comment by FreeTrade** [comment]
Ok added!

**Comment by Real-FEELS** [comment]
Looking at a profile page I can not see any `data-label=` on version 4.5.1.9

**Comment by FreeTrade** [comment]
Hmm, try a shift-reload on that.

**Comment by Real-FEELS** [comment]
Opened in incognito. Still cant see it. It's strange because I can see the new profile picture stuff
<img width="1084" alt="Screenshot 2020-09-27 at 09 04 15" src="https://user-images.githubusercontent.com/68990054/94359645-7ef9ce80-00a0-11eb-944c-20e24b677039.png">

**Comment by FreeTrade** [comment]
might be an intermediate cache - should definitely be there - https://github.com/FreeTrade/memberdev/commit/3715d60ed03b623bb18446c8a1a601a21988cd02

**Comment by Real-FEELS** [comment]
Very strange behaviour. I just cant get it to appear on https://freetrade.github.io/memberdev/ no matter what I do. 

I am also not able to update the profile image (not sure if this is supposed to be working yet)

**Comment by FreeTrade** [comment]
Updating the profile image won't work yet, have to update the server side of things. Next few days I think.

**Comment by FreeTrade** [comment]
i bumped the version up - that might help.

Also updating profile pic should now work on dev server.

**Comment by Real-FEELS** [comment]
Edit: 
I found it under Trust Graph ratings. I was looking at `Ratings By/Of This Member`

**Comment by Real-FEELS** [comment]
Please clean up the titles in the data-labels 

<img width="361" alt="Screenshot 2020-09-28 at 18 30 38" src="https://user-images.githubusercontent.com/68990054/94466152-e60aa680-01b8-11eb-8b52-6caef66064b6.png">

**Comment by FreeTrade** [comment]
Yes, the trust graph is where it is most troublesome on mobile.
Also, my understanding was that the data labels would not be seen? Because problems with localization?

**Comment by Real-FEELS** [comment]
Could you not load the translation into the data-label slot? 

Without the labels, it doesn't make much sense

**Comment by FreeTrade** [comment]
does the css use the data-labels directly? so if they get localized, it won't confuse the css?

**Comment by Real-FEELS** [comment]
Not at all, the CSS is only targeting the label itself ` content: attr(data-label);`

**Comment by Real-FEELS** [comment]
@FreeTrade  please update the text with the next version

**Comment by FreeTrade** [comment]
Done. Also rating star size should be under CSS control now. It will now use the computed font-size of the element that it is placed in.
