### ISSUE TITLE
Preview content

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#24]
for permalinks, member.cash now shows preview content in a div at the top of the page. it is hidden quickly, but might be nice to have a basic style for the quick view - class previewcontent

**Comment by Real-FEELS** [comment]
We could just add `display:none` to `previewcontent` in the CSS?

**Comment by Real-FEELS** [comment]
I would suggest that you add `og:image` and `twitter:image` tags to the DOM. 

If the post has an image link, that could be provided. If not, provide a default image of member.cash logo

**Comment by FreeTrade** [comment]
yes, the image metadata is already provided. will provide the default image of a logo when it's ready.
