### ISSUE TITLE
connection errors now have a class

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#25]
<span class='connectionerror'>

**Comment by Real-FEELS** [comment]
what is the error class?

**Comment by FreeTrade** [comment]
connectionerror lol

**Comment by Real-FEELS** [comment]
Why not implement it on `id="status"`?

**Comment by Real-FEELS** [comment]
Please add some `<p>` tags to the text and wrap `Oops. This request failed.` in a </h1>

**Comment by FreeTrade** [comment]
fixed with next update
