### ISSUE TITLE
Links in posts have additional spacing on either side

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#35]

**Comment by FreeTrade** [comment]
Links in notifications still have issue. Also whitespace at the beginning of notifications text.

My sense is that unusual link default styles are being set, then being overwritten with usual link behavior everywhere else, whereas it is more robust to do it the other way. I worry every time a new link is added with the expectation of default link behavior, styles have to be created to return ordinary link behavior.

**Comment by FreeTrade** [comment]
hmm, these look fixed. maybe i just needed a reload!

**Comment by Real-FEELS** [comment]
I think I will need to add more classes to the items with the memberfilter. Maintaining it is very tedious at the moment.

**Comment by Real-FEELS** [comment]
https://github.com/memberapp/memberapp.github.io/issues/478

https://github.com/memberapp/memberapp.github.io/issues/477

**Comment by FreeTrade** [comment]
Ok. I feel like it could do with a refactoring /simplification. But we're moving onto the twitter style display soon i hope, so maybe not worth the candle.

**Comment by Real-FEELS** [comment]
I'd say thats still a short while off. The above improvements are only small so pass the cost/benefit for me.

**Comment by Real-FEELS** [comment]
The original issue has been fixed
