### ISSUE TITLE
Profile card is not dismissed if mouse exits upwards from card

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#36]

**Comment by FreeTrade** [comment]
moving the card up so that it appears under the mouse pointer will fix this.

**Comment by Real-FEELS** [comment]
https://github.com/FreeTrade/memberdev/pull/53

**Comment by FreeTrade** [comment]
this is still a thing!

**Comment by Real-FEELS** [comment]
Should be fixed with https://github.com/memberapp/FeelsTheme/issues/36

**Comment by Real-FEELS** [comment]
@FreeTrade can you confirm this is fixed?

**Comment by FreeTrade** [comment]
fixed!

**Comment by FreeTrade** [comment]
hmm, related problem - this should be moved further up and to the left. If a user clicks to see the profile page, but the profile card is displayed in the interim, the click goes on white space and nothing happens. move up and left will fix this.

**Comment by Real-FEELS** [comment]
Can you show me a screenshot or some css.

**Comment by FreeTrade** [comment]
hmm, the screenshot doesn't capture the mouse pointer for me. you can replicate it by moving the mouse point over the top of the profile pic, wait half a second, then click, you'll be clicking on white space.

**Comment by Real-FEELS** [comment]
Is that because the card has opened and obstructs the div? 

If you have a css solution please post it here.

**Comment by FreeTrade** [comment]
This will fix it!

.profilepreview {
    top: -1rem;
    left: -1rem;
}
