### ISSUE TITLE
Very long handles break layout.

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#37]
Should probably show very long handles in full on profile page, but truncate elsewhere.
Note this is about handles(names), not pagingids - but there may be similar issues with those

**Comment by Real-FEELS** [comment]
This can be done through CSS. 
Can you wrap all instances off the user name and handles in a div/span `member-handle` and `member-pagingid`

**Comment by FreeTrade** [comment]
ok, that's done

**Comment by Real-FEELS** [comment]
https://github.com/FreeTrade/memberdev/pull/59
