### ISSUE TITLE
Word breaks

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#4]
Personally not a fan of breaking words in the middle -
maybe reconsider 

word-wrap: break-word;

**Comment by FreeTrade** [comment]
or perhaps, only break words for narrow displays?

**Comment by Real-FEELS** [comment]
Do you have an example post?

**Comment by FreeTrade** [comment]
![Capture](https://user-images.githubusercontent.com/5759305/91923082-110cf200-ed02-11ea-802f-f165ed797c4e.PNG)

**Comment by Real-FEELS** [comment]
Should be fixed with latest PR
