### ISSUE TITLE
Bunching up text on thread page on mobile

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#44]
https://member.cash/p/cfc7ce2d3e

**Comment by FreeTrade** [comment]
I think I should move the ' 4 likes and 4096 sats 14 hours ago' to the footer.

**Comment by Real-FEELS** [comment]
Or move all that info to the header?

**Comment by FreeTrade** [comment]
I think in the footer. With the twitter theme it'll be in the footer so might as well keep consistent

**Comment by Real-FEELS** [comment]
Really looking forward to a better DOM structure!

**Comment by FreeTrade** [comment]
Do you have any idea for a name for the new theme?

**Comment by Real-FEELS** [comment]
could call it the `Feed` theme, or `Morden social`

**Comment by Real-FEELS** [comment]
Perhaps the rating could be removed and only seen on the profile page and the profilepreview

**Comment by FreeTrade** [comment]
Feed might be a little confusing as it duplicates a function of the site.

**Comment by Real-FEELS** [comment]
https://github.com/FreeTrade/memberdev/pull/59 its not a perfect solution but will do for now until you move the `4 likes and 4096 sats 14 hours ago` to the footer
