### ISSUE TITLE
pop up on map has horizontal scrollbar

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#49]

**Comment by Real-FEELS** [comment]
Can not duplicate. Do you have a link for the offending map item

**Comment by FreeTrade** [comment]
![map](https://user-images.githubusercontent.com/5759305/95733040-25a2b980-0cb4-11eb-9b2d-dd02dbd4a1f5.PNG)
here's what i'm seeing. also the X on the top right is over the scroll bar

**Comment by Real-FEELS** [comment]
What browser / os?

**Comment by FreeTrade** [comment]
Firefox /windows 10

**Comment by Real-FEELS** [comment]
hmm, I cant replicate it as Im using a mac. 

Moving the X is fine, but i'm not sure what to do about the disabled horizontal scrollbar 

<img width="319" alt="Screenshot 2020-10-16 at 08 32 33" src="https://user-images.githubusercontent.com/68990054/96226213-3a1fd400-0f8a-11eb-9bd1-9e6ecacdd43d.png">

**Comment by Real-FEELS** [comment]
Check the fix I pushed

**Comment by FreeTrade** [comment]
both fixed, thank you!
