### ISSUE TITLE
follower buttons break on profile card if 3 digits

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#53]
![follows](https://user-images.githubusercontent.com/5759305/96207752-8c6af000-0f9e-11eb-89fe-b33151e5b326.png)

**Comment by Real-FEELS** [comment]
looks fine to me

<img width="442" alt="Screenshot 2020-10-16 at 08 06 23" src="https://user-images.githubusercontent.com/68990054/96223912-9c76d580-0f86-11eb-9857-4fa5b7219f9e.png">
<img width="444" alt="Screenshot 2020-10-16 at 08 06 56" src="https://user-images.githubusercontent.com/68990054/96223914-9d0f6c00-0f86-11eb-89a2-19805a087078.png">

**Comment by Real-FEELS** [comment]
I have identified the issue. Please give the `Send Message` button a class of `populate-send-message` or similar 

<img width="758" alt="Screenshot 2020-10-16 at 08 11 15" src="https://user-images.githubusercontent.com/68990054/96224266-32126500-0f87-11eb-8938-b9c59179588d.png">

**Comment by FreeTrade** [comment]
done
