### ISSUE TITLE
Quote Remembers are live on the dev server and need some TLC

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#57]

**Comment by Real-FEELS** [comment]
I am on Version 4.12.3 - what is the flow for Quote Remembers

**Comment by FreeTrade** [comment]
So there's a link/button 'quote' under each post now. This takes you to the compose page with the post shown underneath.

**Comment by Real-FEELS** [comment]
https://github.com/FreeTrade/memberdev/pull/64

**Comment by FreeTrade** [comment]
I think when quoting another post, maybe have a border box around the post, like twitter.

When remembering a post, with no additional content, maybe a lot less emphasis on the remembering user - no profile pic, just a small remember icon on a single line - again like twitter.

**Comment by Real-FEELS** [comment]
You would need to add another class to the post when that is the case

**Comment by FreeTrade** [comment]
should be a 'repost' class around those.

also, think we don't need the rounded box around a regular remember, only for the quote remember

**Comment by Real-FEELS** [comment]
`repost` class only covers the title. I need a class that covers both the title `quotepost` on the `li` element

**Comment by FreeTrade** [comment]
should have this class now - i couldn't add it to the li element, but should be a span or div now to cover both

**Comment by Real-FEELS** [comment]
Check the latest PR. Let me know if you want more changes.

**Comment by FreeTrade** [comment]
ok, thanks - not seeing a PR yet tho
