### ISSUE TITLE
selected comment is not highlighted

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#6]
When a user clicks on a comment through to a thread page, the comment can be difficult to find, so it has a special class highlighted to make it more visible -

<div class="reply highlight" id="highlightedcomment">

however theme doesn't highlight the comment

**Comment by Real-FEELS** [comment]
what class is added tot he highlighted comment?

**Comment by Real-FEELS** [comment]
Fixed with https://github.com/FreeTrade/memberdev/pull/28

**Comment by FreeTrade** [comment]
can't see any highlighting?

**Comment by Real-FEELS** [comment]
looks fine to me 
<img width="991" alt="Screenshot 2020-09-02 at 09 51 12" src="https://user-images.githubusercontent.com/68990054/91960538-e58a0780-ed01-11ea-871a-bb82eec2a010.png">

**Comment by FreeTrade** [comment]
hmm, maybe the color difference is too subtle for my monitor to pick up (that's happened to me before!) - what form of highlighting are you seeing?

**Comment by Real-FEELS** [comment]
Ok i updated the shade

<img width="847" alt="Screenshot 2020-09-02 at 10 16 55" src="https://user-images.githubusercontent.com/68990054/91963191-731b2680-ed05-11ea-959d-c8bb1cf963f4.png">
