### ISSUE TITLE
highlighted notification now has 'highlighted' class

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#60]

**Comment by Real-FEELS** [comment]
Where can i see this?

**Comment by FreeTrade** [comment]
hmm, it's not live yet on main site yet, so difficult to demonstrate, but when you click on a notification, it'll bring you to the notification page and scroll to the correct notification which will also be highlighted

**Comment by Real-FEELS** [comment]
Ok I have added a class for `.highlighted`  - will test more once it's live

**Comment by FreeTrade** [comment]
Ok, it's live now

**Comment by FreeTrade** [comment]
i'm not seeing any highlight effect? is there some css there

**Comment by Real-FEELS** [comment]
I am not able to create the scenario where i see this class. 

Can you show me the dom structure.

**Comment by FreeTrade** [comment]
just caught one - 

```
<ul class="notificationslist">
    <li class="highlighted notificationitem notificationtopic" id="notification574c88d603606eaf1f0146d1f158bd51d094bf0625460fc9456061e76770cb49">
        <div class="notificationdetails">
        <div class="notificationminheight">
            <div class="notificationtitle">

the highlighted is on the <li>
```

**Comment by Real-FEELS** [comment]
This should solve it.
