### ISSUE TITLE
collection of small issues

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#65]
I had to move some html around to support the localization - resulted in a few things  being kicked out of kilter -

-profile images are a little squashed
-version4.15 - missing space 
https://freetrade.github.io/memberdev/img/logos/logowide.svg - this svg is broken on some platforms
-space between rating and topic too big - feels
-ranking too close to topic
-remember button out of place
-size of qr codes
-too much padding on the inside of ranking buttons now

-hopefully these are the last changes for the feels theme, at least before the v5 release

**Comment by Real-FEELS** [comment]
cannot replicate `profile images are a little squashed`

**Comment by Real-FEELS** [comment]
Not sure how I can fix this `https://freetrade.github.io/memberdev/img/logos/logowide.svg - this svg is broken on some platforms`

**Comment by Real-FEELS** [comment]
-too much padding on the inside of ranking buttons now - this is due to the flair class being repeated. Remove the nested flair class.
