### ISSUE TITLE
On mobile, on the topics list, maybe hide the two middle columns

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#67]

**Comment by FreeTrade** [comment]
new update seems to cut off half the table, rather than hide the columns

**Comment by FreeTrade** [comment]
Maybe i'm misunderstanding something here. I was expecting the middle two columns to disappear when reducing width of browser, but instead the right side of the table became truncated. I reverted, but this didn't change the behavior, so i guess this behavior was there before. Tested reducing width on desktop rather than mobile btw.

**Comment by Real-FEELS** [comment]
Updated the media query to target tablet size and below.
