### ISSUE TITLE
Add filter buttons are messed up - unclear how to use

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#7]
See on topics page

**Comment by Real-FEELS** [comment]
<img width="770" alt="Screenshot 2020-09-01 at 11 58 29" src="https://user-images.githubusercontent.com/68990054/91841565-81583c80-ec4a-11ea-88a7-937719536f0f.png">
 this?

**Comment by FreeTrade** [comment]
Yes, it's unclear which buttons relate to which filters

**Comment by Real-FEELS** [comment]
<img width="561" alt="Screenshot 2020-09-02 at 08 54 14" src="https://user-images.githubusercontent.com/68990054/91954684-0d756d00-ecfa-11ea-8ede-a9034cb69a69.png">

Can you please wrap each filter group with in div with the class `filterprovider` or something like that.

**Comment by FreeTrade** [comment]
done

**Comment by Real-FEELS** [comment]
Please wrap `( {{USERNAME}} )`  in a div eg `member` or `filterby`

**Comment by FreeTrade** [comment]
ok - called membercontainer

**Comment by Real-FEELS** [comment]
`filterprovider` DOM is incorrect. Currently each `filterprovider` in nested inside another `filterprovider`

**Comment by FreeTrade** [comment]
ok, fixing

**Comment by Real-FEELS** [comment]
memberfilter should div should also include the brackets `( )`

**Comment by FreeTrade** [comment]
hmmm, would span work as well for you? these divs are displayed as block, and we mostly need them inline i think

**Comment by Real-FEELS** [comment]
yeah span is fine

**Comment by Real-FEELS** [comment]
Please add the class `unsubscribe` to the `unsubscribe` button. This way it can have it's own color

**Comment by FreeTrade** [comment]
added. if you need to add new spans/divs or classes, please feel free, just don't reflow the document so i can see easily what's been added in the diff.

**Comment by Real-FEELS** [comment]
Is the code for that within the HTML or a JS file?

**Comment by FreeTrade** [comment]
i think both additions were in js files today
