### ISSUE TITLE
Add different color for visited link

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#76]

**Comment by Real-FEELS** [comment]
@FreeTrade current link formatting is like this:

```
<div class="title" onclick="if(document.getSelection().type === 'Range'){return;}else{location.href='#thread?root=4ab104b5f1a9f7aefa10d0e9174aab0a9e78b7ac30890470896a0a40a62534d5&amp;post=4ab104b5f1a9f7aefa10d0e9174aab0a9e78b7ac30890470896a0a40a62534d5'};">
            <p>... </p>
</div>
```

CSS `:visited` selector does not work on these links. Suggest adding a class to the link if the user has visited the link before. Save it in local storage. This could be a privacy issue so I suggest you also add a toggle in the settings for this feature.

**Comment by FreeTrade** [comment]
Thanks. I don't think js has access to this information for privacy reasons, so maybe we can't do this at all.
