### ISSUE TITLE
greyed out buttons should not have mouse hand icon

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#8]

**Comment by Real-FEELS** [comment]
fixed with latest PR

**Comment by FreeTrade** [comment]
disabled button still gets an active mouse over hand icon -

**Comment by Real-FEELS** [comment]
Which disabled button are you referring to?

**Comment by FreeTrade** [comment]
on the settings page - update handle/profile

**Comment by Real-FEELS** [comment]
Fixed with https://github.com/FreeTrade/memberdev/pull/31
