### ISSUE TITLE
In notifications, star rating not well horizontally aligned with username

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#9]

**Comment by FreeTrade** [comment]
Also in encrypted messages

**Comment by Real-FEELS** [comment]
Fixed with https://github.com/FreeTrade/memberdev/pull/38

I need you to add a div to the messages where the red box is. called `messagemeta` or something like that.

**Comment by FreeTrade** [comment]
done.

**Comment by Real-FEELS** [comment]
Fixed with https://github.com/FreeTrade/memberdev/pull/39
